### ISSUE TITLE
一个小BUG

### ISSUE THREAD

**Issue by yzddmr6** [Medicean/as_bypass_php_disable_functions#1]
经过测试
如果当前的shell后面有传入的参数时,新生成的.antproxy.php中不会加上
例如:
http://www.xxx.com/a.php?test=assert
这个shell

生成的.antproxy.php中的第四行没有加入get的参数,就会导致连接失败
`curl_setopt($aAccess, CURLOPT_URL, "http://127.0.0.1:63685/a.php");`

**Comment by Medicean** [comment]
fixed
