### ISSUE TITLE
php5.6.40下两个BUG

### ISSUE THREAD

**Issue by ljycrystal** [Medicean/as_bypass_php_disable_functions#3]
1. 日志报错
> [Sun Jun 23 10:41:15.880997 2019] [:error] [pid 32465] [client 169.254.65.200:63206] PHP Fatal error:  Call to undefined function curl_init() in /var/www/html/xxxx/yyyy/.antproxy.php on line 3

这一行是
`$aAccess = curl_init();`
我ubuntu18.04在
> sudo apt install php5.6-curl
> service apache2 restart

后可以了。但是这个不符合此前假设
>  目标机器无法主动外连，并且入站只有80端口可访问，目标机器上面不保证一定有python, 不一定有 perl。我们能肯定的是，应该是有php的，但美中不足的是PHP在5.4版本才引入了 -S 这个内置web服务器

的条件

2. 在
`list($headerstr,$sResponse)=explode("\r\n\r\n",$sResponse, 2);`
报错，日志为：
> [Sun Jun 23 11:41:45.137806 2019] [:error] [pid 681] [client 169.254.65.200:50174] PHP Notice:  Undefined offset: 1 in /var/www/html/xxxx/yyyy/.antproxy.php on line 58

用is_bool看了下，$sResponse是个bool值

**Comment by Medicean** [comment]
这个 proxy 的脚本用的是 curl，你可以换成 fsocket 写

**Comment by Medicean** [comment]
已经支持  fsock 方式，优先采用 curl
