### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by yzddmr6** [Medicean/as_bypass_php_disable_functions#4]
本来是可以bypass的，但是后来上了waf，第二次写入代理脚本的时候就被拦截了
![image](https://user-images.githubusercontent.com/46088090/68573571-f6336d80-04a2-11ea-9292-846ea4869038.png)
经过检查此目录有读写权限
![image](https://user-images.githubusercontent.com/46088090/68573665-23801b80-04a3-11ea-85c6-a30254f6eeb4.png)

于是想到蚁剑的代理脚本特征很有可能已经进了waf的规则查杀库，所以插件无法正常使用

个人建议是可以把生成的代理php脚本打印出来，用户可以根据需要复制粘贴，再进行进一步的混淆处理，希望能够采纳，谢谢。

**Comment by Medicean** [comment]
代理脚本是没啥特征的，就是单纯的上传了文件而已，你可以自己抠出来：

https://github.com/Medicean/as_bypass_php_disable_functions/blob/master/payload.js#L343-L409

你这个情况，估计是 WAF 上有 CC防护，一顿操作下来，触发了 CC

**Comment by yzddmr6** [comment]
感谢回复
刚才抠出来后再单独上传就可以了

**Comment by yzddmr6** [comment]
emmmmmm 我又来请教问题了
