### ISSUE TITLE
求ext里面的so文件源代码

### ISSUE THREAD

**Issue by Imtinmin** [Medicean/as_bypass_php_disable_functions#5]
我看到php-fpm里面需要用到so文件来启动一个php server，想问一下so文件的源代码可以供学习参考一下吗

**Comment by Medicean** [comment]
拖进ida，看到的就是源码

**Comment by Medicean** [comment]
其实就是在so里有init函数，只要被加载就会执行

**Comment by Medicean** [comment]
https://blog.csdn.net/q327611906/article/details/38897113
