### ISSUE TITLE
插件获取不到shell状态怎么解决?

### ISSUE THREAD

**Issue by ghost** [Medicean/as_bypass_php_disable_functions#6]
linux环境.使用插件的时候提示需要linux系统,
右边的shell状态获取不到.提示错误.

**Comment by Medicean** [comment]
https://github.com/Medicean/as_bypass_php_disable_functions/blob/master/payload.js#L317

**Comment by ghost** [comment]
@Medicean  我在shell下面新建了个php echo了一下php_uname('s').是正常输出linux的.应该不是函数禁用了. 为什么插件获取不到啊.antsword打开插件的时候提示错误,操作失败{}

**Comment by Medicean** [comment]
自己抓包看一下就知道了

**Comment by ghost** [comment]
是我antsword版本的问题..
