### ISSUE TITLE
建议.antproxy.php文件上传到当前shell目录

### ISSUE THREAD

**Issue by M00nT0** [Medicean/as_bypass_php_disable_functions#9]
建议.antproxy.php文件上传到当前shell目录，有时候根目录不可写。
使用FASTCGI的方式bypass显示so文件上传成功，但是代理脚本上传失败，发现重新启的FPM端口是开启的，自己上传.antproxy.php修改连接端口，一连接FPM端口就没了

**Comment by Medicean** [comment]
根目录不可写这种情况下手动上传就行。

如果自动写到当前目录下的话，主要是添加新的 shell 数据时，使用者得清楚在哪个目录下，掌握插件原理才能应用自如，出于这层考虑，所以使用了现在的方式。你可以自己修改插件内代码。

**Comment by Gofreedom0** [comment]
> 根目录不可写这种情况下手动上传就行。
> 
> 如果自动写到当前目录下的话，主要是添加新的 shell 数据时，使用者得清楚在哪个目录下，掌握插件原理才能应用自如，出于这层考虑，所以使用了现在的方式。你可以自己修改插件内代码。

**Comment by Gofreedom0** [comment]
> 根目录不可写这种情况下手动上传就行。
> 
> 如果自动写到当前下的话，主要是添加新的外壳数据时，你可以清楚地在哪个目录下，掌握插件原理才能应用自如，从这层考虑，所以使用现在的方式。你可以自己了修改插件内代码。

干

**Comment by M00nT0** [comment]
> 根目录不可写这种情况下手动上传就行。
> 
> 如果自动写到当前目录下的话，主要是添加新的 shell 数据时，使用者得清楚在哪个目录下，掌握插件原理才能应用自如，出于这层考虑，所以使用了现在的方式。你可以自己修改插件内代码。

"添加新的 shell 数据时，使用者得清楚在哪个目录下"，如果是创建当前webshell的副本，然后去修改地址连接.antproxy.php应该不会太麻烦把~~

根目录不可写的话，.antproxy.php上传不上去，意味着由插件生成的php代码中的一些随机数据不知道，比如说在目标上重新启的FASTCGI端口。我是用了另一个看网络连接的插件去看的端口，然后替换了.antproxy.php然后再自己修改了里面的一些随机数据..

我也尝试修改了base.js中的 ``` path: `${self.top.infodata.phpself}/.antproxy.php`, ```为绝对路径，.antproxy.php也上传到了当前shell路径，但是还是不行噢~

**Comment by Medicean** [comment]
已经改为当前目录
